# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: xenial
latex: false

branches:
  only:
    - src

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'blogdown::build_site()'

deploy:
  repo: petrbouchal/petrbouchal.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: src
  local_dir: public
