baseURL = "https://petrbouchal.github.op"
title = "Petr Bouchal"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-42949500-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = false
pygmentsStyle = "tango"

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "cz"

[params.info]
description = "Petr Bouchal"
title404 = "Tady nic není!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Petr Bouchal"
startYear = "2019"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = false

[params.widgets]
homepage = ["about", "recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "pbouchal@gmail.com"
github = "petrbouchal"
linkedin = "petrbouchal"
twitter = "petrbouchal"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "MunifTanjim"
repository = "minimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"
posts = "/:year/:month/:title/"

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/petrbouchal/petrbouchal.github.io"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.cz]
lang = "cz"
languageName = "Czech"
weight = 1
