on:
  push:
    branches: src

name: blogdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install XQuartz on MacOS
        if: runner.os == 'macOS'
        run: brew install --cask xquartz

      - name: Install cairo
        if: runner.os == 'macOS'
        run: brew install cairo

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: renv for packages
        uses: r-lib/actions/setup-renv@v2

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo(version = "0.79.0")'

      - name: Install theme via submodule
        run: |
          git submodule sync && git submodule update --init

      - name: Build site
        run: |
          R -e 'blogdown::build_site()'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: master
